export const osKeys = ["direction", "performance", "money", "reward", "talent", "aiExecution"];

export const initialState = {
  language: "en",
  activeStep: "journey",
  submitted: false,
  pre: {
    company: "BrightCare Dental Group Sdn. Bhd.",
    industry: "Multi-branch dental clinic",
    participants: "Dr. Tan, Managing Director; Melissa, Operations Manager",
    decisionMaker: "Dr. Tan",
    executionOwner: "Melissa",
    direction: "Become the most trusted and responsive multi-branch dental group in Cheras.",
    problem: "WhatsApp enquiries are fragmented across branches and the first response is slow.",
    baseline: "Average first response: 4 hours",
    target: "Average first response: 15 minutes or less",
    dataSource: "WhatsApp Business export and weekly branch tracker",
    monthlyVolume: 420,
    conversionRate: 18,
    targetConversionRate: 24,
    averageValue: 280,
    consent: true,
  },
  diagnostic: {
    stageRatings: [2, 4, 2, 2, 1],
    osRatings: { direction: 4, performance: 3, money: 4, reward: 2, talent: 3, aiExecution: 3 },
    stageEvidence: [
      { note: "Owner still resolves cross-branch exceptions.", source: "Workshop interview" },
      { note: "Core SOPs exist for reception and appointments.", source: "SOP index" },
      { note: "KPIs are reviewed but rewards are not consistently linked.", source: "Weekly tracker" },
      { note: "Reports are consolidated weekly, not daily.", source: "Google Sheet" },
      { note: "ChatGPT is used individually; no governed workflow exists.", source: "Participant interview" },
    ],
    osEvidence: {
      direction: { note: "12-month direction is stated and understood by management.", source: "Management plan" },
      performance: { note: "Branch KPIs exist but accountability varies.", source: "KPI tracker" },
      money: { note: "Lead, appointment and treatment value are measured.", source: "Sales report" },
      reward: { note: "Recognition is informal and not tied to weekly actions.", source: "Interview" },
      talent: { note: "Branch roles exist; development paths are incomplete.", source: "Organisation chart" },
      aiExecution: { note: "Three candidate workflows identified; none deployed.", source: "Workshop notes" },
    },
    bottlenecks: [
      { issue: "Slow WhatsApp lead response", impact: "Prospects move to competitors", owner: "Customer Care Lead" },
      { issue: "Weak appointment confirmation", impact: "Chair capacity and revenue are lost", owner: "Clinic Manager" },
      { issue: "Late branch performance data", impact: "Corrective action starts too late", owner: "Operations Manager" },
    ],
  },
  plan: {
    result: "Reduce average first response time from 4 hours to 15 minutes or less.",
    weeklyAction: "Review unassigned leads and SLA exceptions every Friday at 4:30pm.",
    metric: "Median first-response time and lead assignment rate",
    reward: "Monthly recognition for the branch that sustains the response SLA",
    owner: "Customer Care Lead",
    day1: "Confirm definitions, owners, data sources and the 90-day target.",
    day30: "Launch the lead-response workflow and weekly review.",
    day60: "Optimise assignment rules, replies and exception handling.",
    day90: "Validate results, standardise the SOP and decide whether to scale.",
    primaryProduct: "Vimigo For Team 2.0",
    productReason: "The immediate gap is consistent team execution and accountability across branches.",
    expectedResult: "Direction becomes visible weekly actions, owners, measures and recognition.",
    reviewDate: "2026-10-18",
    workspaceConfirmed: false,
    workspaceName: "",
    hypotheses: [
      { opportunity: "Centralise lead ownership", assumption: "Response delay is mainly caused by fragmented intake.", validation: "Pilot one intake queue for 30 days.", metric: "Median response time" },
      { opportunity: "Protect appointment capacity", assumption: "Structured reminders can reduce avoidable no-shows.", validation: "Test 48/24-hour confirmations in one branch.", metric: "No-show rate" },
      { opportunity: "Standardise branch review", assumption: "Faster visibility will improve corrective action.", validation: "Run a D+1 dashboard and weekly review.", metric: "Review completion rate" },
    ],
  },
};
