export const osKeys = ["direction", "performance", "money", "reward", "talent", "aiExecution"];

export const initialState = {
  language: "en",
  activeStep: "journey",
  submitted: false,
  pre: {
    company: "BrightCare Dental Group Sdn. Bhd.",
    industry: "Multi-branch dental clinic",
    participants: "Dr. Tan, Managing Director; Melissa, Operations Manager",
    decisionMaker: "Dr. Tan",
    executionOwner: "Melissa",
    direction: "Become the most trusted and responsive multi-branch dental group in Cheras.",
    problem: "WhatsApp enquiries are fragmented across branches and the first response is slow.",
    baseline: "Average first response: 4 hours",
    target: "Average first response: 15 minutes or less",
    dataSource: "WhatsApp Business export and weekly branch tracker",
    monthlyVolume: 420,
    conversionRate: 18,
    targetConversionRate: 24,
    averageValue: 280,
    consent: true,
  },
  diagnostic: {
    stageRatings: [2, 4, 2, 2, 1],
    osRatings: { direction: 4, performance: 3, money: 4, reward: 2, talent: 3, aiExecution: 3 },
    bottlenecks: [
      { issue: "Slow WhatsApp lead response", impact: "Prospects move to competitors", trigger: "A new WhatsApp enquiry is received", inputs: "Enquiry text, branch, service requested, operating hours and approved reply rules", aiTask: "Classify intent, summarise the enquiry and draft the next approved response", humanApproval: "Customer Care Lead approves sensitive, unusual or high-value replies", owner: "Customer Care Lead", exceptions: "Clinical advice, complaints, refunds and messages with unclear consent route to a human", metric: "Median first-response time and lead assignment rate", readiness: "Medium - message data exists but routing rules need standardisation", risk: "Incorrect or inappropriate customer-facing reply" },
      { issue: "Weak appointment confirmation", impact: "Chair capacity and revenue are lost", trigger: "An appointment reaches the 48-hour and 24-hour confirmation windows", inputs: "Appointment time, branch, patient contact preference and approved reminder template", aiTask: "Prepare reminder and confirmation follow-up tasks using approved templates", humanApproval: "Clinic Manager approves rescheduling, complaints and special-care cases", owner: "Clinic Manager", exceptions: "Medical questions, repeated no-response and rescheduling conflicts route to staff", metric: "Confirmation completion rate and no-show rate", readiness: "Medium - appointment data exists but consent and exception rules require review", risk: "Privacy, consent or incorrect appointment information" },
      { issue: "Late branch performance data", impact: "Corrective action starts too late", trigger: "The daily reporting cut-off is reached", inputs: "Approved branch KPI records, ownership list, targets and exception thresholds", aiTask: "Summarise KPI variance, identify missing updates and draft an exception digest", humanApproval: "Operations Manager validates exceptions before management circulation", owner: "Operations Manager", exceptions: "Missing, disputed or materially abnormal data is held for manual validation", metric: "D+1 report completion and exception-closure rate", readiness: "Medium - source data exists but definitions and cut-off discipline vary", risk: "Management decisions based on incomplete or inconsistent data" },
    ],
  },
  plan: {
    result: "Reduce average first response time from 4 hours to 15 minutes or less.",
    weeklyAction: "Review unassigned leads and SLA exceptions every Friday at 4:30pm.",
    metric: "Median first-response time and lead assignment rate",
    reward: "Monthly recognition for the branch that sustains the response SLA",
    owner: "Customer Care Lead",
    day1: "Confirm definitions, owners, data sources and the 90-day target.",
    day30: "Launch the lead-response workflow and weekly review.",
    day60: "Optimise assignment rules, replies and exception handling.",
    day90: "Validate results, standardise the SOP and decide whether to scale.",
    primaryProduct: "Vimigo For Team 2.0",
    productReason: "The immediate gap is consistent team execution and accountability across branches.",
    expectedResult: "Direction becomes visible weekly actions, owners, measures and recognition.",
    reviewDate: "2026-10-18",
    workspaceConfirmed: false,
    workspaceName: "",
    hypotheses: [
      { opportunity: "Centralise lead ownership", assumption: "Response delay is mainly caused by fragmented intake.", upside: "Faster response, clearer ownership and fewer unassigned enquiries.", validation: "Pilot one intake queue for 30 days.", metric: "Median response time" },
      { opportunity: "Protect appointment capacity", assumption: "Structured reminders can reduce avoidable no-shows.", upside: "More usable chair capacity and fewer avoidable schedule gaps.", validation: "Test 48/24-hour confirmations in one branch.", metric: "No-show rate" },
      { opportunity: "Standardise branch review", assumption: "Faster visibility will improve corrective action.", upside: "Earlier intervention and more consistent branch execution.", validation: "Run a D+1 dashboard and weekly review.", metric: "Review completion rate" },
    ],
  },
};
